service: mdl-api

custom:
  region: 'us-east-1'

provider:
  name: aws
  region: ${self:custom.region}
  memorySize: 512
  timeout: 30
  runtime: nodejs10.x

functions:
  query:
    handler: handler.query
    events:
      - http:
          path: q/{q}
          method: get
          cors: true
          request:
            parameters:
              paths:
                q: true